<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.docod.print</groupId>
        <artifactId>dc-print-api</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>dc-print-dependencies</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>统一依赖管理</description>

    <properties>
        <spring.boot.version>2.7.18</spring.boot.version>
        <mybatis-plus.version>3.5.3.1</mybatis-plus.version>
        <dynamic-datasource.version>3.6.1</dynamic-datasource.version>
        <druid.version>1.2.21</druid.version>
        <mysql.version>8.0.33</mysql.version>
        <redis.version>2.7.18</redis.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- DB -->
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
                <version>${dynamic-datasource.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <!-- 内部模块 -->
            <dependency>
                <groupId>com.docod.print</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.docod.print</groupId>
                <artifactId>spring-boot-starter-mybatis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.docod.print</groupId>
                <artifactId>spring-boot-starter-security</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.docod.print</groupId>
                <artifactId>spring-boot-starter-biz-tenant</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.docod.print</groupId>
                <artifactId>spring-boot-starter-redis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.docod.print</groupId>
                <artifactId>dc-print-module-system</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
